name: Bug
description: Report something broken or incorrect
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: Include expected vs actual behavior.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: How to reproduce
      description: Minimal steps (or a small repo/branch).
      placeholder: |
        1) ...
        2) ...
        3) ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / errors
      description: Paste relevant output (redact secrets).

